version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: next-seo
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.22.0
    - 4.23.0
  - dependency-name: next-offline
    versions:
    - 5.0.3
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: react-dom
    versions:
    - 16.13.0
